### ISSUE TITLE
Too many arguments for function: <SNR>55_on_timer

### ISSUE THREAD

**Issue by jessemillar** [roxma/vim-paste-easy#1]
I installed `vim-paste-easy` via `vim-plug` and added `autocmd VimEnter * PasteEasyEnable` to my `.vimrc`. When pasting, `vim-paste-easy` goes into paste mode, but then flashes the following message at the bottom of my `vim` window (and prevents moving the cursor or exiting insert mode) until I mash on some keys.

```
E118: Too many arguments for function: <SNR>55_on_timer
```

Tested on macOS 10.12.2 (16C67) in VIM 8.0 (2016 Sep 12, compiled Jan  3 2017 05:43:41) using the [Hyper terminal emulator](https://hyper.is/) (Version 1.1.0 (1.1.0.1408)).

**Comment by roxma** [comment]
@jessemillar 

Checkout the latest code and see if it is still happening.

**Comment by jessemillar** [comment]
Seems to be working. Tested the latest code on macOS and Linux. No problems on either. Thanks!
