### ISSUE TITLE
Incompatible with v:version <= 704

### ISSUE THREAD

**Issue by rafaeln** [roxma/vim-paste-easy#10]
My workaround is to check in my .vimrc and disable the plugin in older versions, but I thought I'd let you know about this and you might want to state minimum version somewhere in the readme or maybe have the plugin not load and issue a message whenever a user tries to run it in a version of vim that doesn't support it. The relevant function that is absent from 7.4 seems to be reltimefloat

**Comment by roxma** [comment]
Now it fallbacks to `reltimestr`, please test it.

**Comment by rafaeln** [comment]
Before I was getting errors as soon as I got in insert mode and typed the first character, now I'm getting errors as I leave insert mode. What I get is:

    paste-easy end
    Error detected while processing function <SNR>55_stop_easy_paste:
    line   12:
    E168: :finish used outside of a sourced file

**Comment by roxma** [comment]
It seems the vim distribution doesn't have timer.

I've pushed another update to fix the error.

**Comment by rafaeln** [comment]
This now works. My 2009 MacBook running the latest version of vim installable through TigerBrew under MacOS 10.6.9 is happy now.
