### ISSUE TITLE
Conflicts with terryma/vim-multiple-cursors

### ISSUE THREAD

**Issue by santiagodoldan** [roxma/vim-paste-easy#4]
![test](http://g.recordit.co/JHDlEvUCJ0.gif)

**Comment by roxma** [comment]
this may help: https://github.com/terryma/vim-multiple-cursors#multiple_cursors_beforemultiple_cursors_after-default-nothing

```vim
function! Multiple_cursors_before()
  PasteEasyDisable 
endfunction

function! Multiple_cursors_after()
    PasteEasyEnable
endfunction
```

**Comment by santiagodoldan** [comment]
Yep, that fixed the issue, thanks 👍
