### ISSUE TITLE
"paste-easy end" is too noisy

### ISSUE THREAD

**Issue by bennyyip** [roxma/vim-paste-easy#5]
https://github.com/roxma/vim-paste-easy/blob/master/plugin/paste-easy.vim#L74
This line flushes `:messages`. Maybe we should remove it?

**Comment by roxma** [comment]
This is intentional.

Auto modifying paste mode may produce undesired behavior, in such case, this message is useful for finding which plugin is controling this behavior.

You could send PR, add option to disable it. (enable by default)
