### ISSUE TITLE
Conflicts with maralla/completor.vim when `g:completor_auto_trigger` is on

### ISSUE THREAD

**Issue by bennyyip** [roxma/vim-paste-easy#7]
When `g:completor_completion_delay ` is lower than 0.01s(default is 80ms), and user copy some text that may trigger completion, there will be a "<Plug>CompletorTrigger" on the end of the copied text. This is because completion is trigger in paste mode. For example,  

input:  
```
mode
```

ouput:  
```
 mode<Plug>CompletorTrigger
```

One way to fix this is to set `g:completor_completion_delay` higher, like 200ms, or turn auto trigger off, but this results in bad user experience.  
Another way is add `CompletorDisable` and `CompletorEnable` in ` s:start_easy_paste()` and ` s:stop_easy_paste()`. But this solution is quiet hacky, though we already do something like this for MultipleCursors.   

Maybe not only completor has this problem, other auto trigger complete plugin may suffer from this too.

**Comment by roxma** [comment]
I guess this is completor issue, completor should check the `&paste` flag before feeding  `<Plug>CompletorTrigger`  @maralla

similar issue on ncm: https://github.com/roxma/nvim-completion-manager/issues/78

**Comment by bennyyip** [comment]
多谢指教，我给completor那边发PR了。
